### ISSUE TITLE
Compatibility with different devices

### ISSUE THREAD

**Issue by PalakShah93** [raja95shah/weddingpro#2]
The font, animation and items position not compatible with all devices

For Font, You may consider below link which contains some font which are acceptable by most of the devices.
https://www.template.net/design-templates/web-elements/45-stunning-android-fonts-make-your-device-more-lookable/

**Comment by raja95shah** [comment]
Do write some suggested solutions for us to take note.

**Comment by PalakShah93** [comment]
Okay Noted.....

On Mon, Apr 4, 2016 at 1:45 PM, Smit Shah <notifications@github.com> wrote:

> Do write some suggested solutions for us to take note.
> On 4 Apr 2016 13:38, "PalakShah93" <notifications@github.com> wrote:
>
> > The font, animation and items position not compatible with all devices
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/raja95shah/weddingpro/issues/2>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/raja95shah/weddingpro/issues/2#issuecomment-205145488>
>



-- 
*Regards & Thanks*
*Shah Palak *

*(M) +65 87770297 | (Email) palak@createappasia.com
<palak@createappasia.com> | Website: www.iampalakshah.com
<http://www.iampalakshah.com>*
